services:
  web:
    image: nginx
    container_name: nginx_serveur
    hostname : nginx_serveur
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/var/www/html
      - ./certificate/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./certificate/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - dmz
  db:
    image: mariadb
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${USER_PASS}
    volumes:
      - ./DB/sql:/docker-entrypoint-initdb.d
      - ./DB/conf/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - db_net
  php:
    image: php
    container_name: php
    hostname: php
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${PHP_USER}
      MYSQL_PASSWORD: ${PHP_PASS}
      MYSQL_HOST: ${PHP_HOST}
    volumes:
      - ./html:/var/www/html
    networks:
      - dmz
      - db_net
  certbot:
    image: certbot/certbot:v2.6.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  dmz:
  db_net:
