on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ubuntu-latest] 
    steps: 
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Push to server 
        uses: appleboy/ssh-action@master
        with:
          host: '54.37.12.151'
          username: 'alois'
          password: 'Je suis un he202277'
          port: 55555
          script: pkill -f "python3 app.py" && cd ~/admin-II/Automate\ scirpt\ to\ check\ all\ network/ && git fetch origin && git pull & cd ~/admin-II/Automate\ scirpt\ to\ check\ all\ network/ && sleep 10 && python3 app.py
